# Generated by Django 5.0.4

import bakery.models
import cloudinary.models
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_promotion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=bakery.models.generate_order_number, max_length=20, unique=True, verbose_name='เลขออเดอร์'),
        ),
    ]
