# Generated by Django 5.0.4

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0007_productsku_image_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ยกเลิก'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('confirmed', 'ยืนยันแล้ว'), ('done', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิกแล้ว')], default='pending', max_length=20),
        ),
    ]
